parameter_server:
  ros__parameters:
    car_id: JoeBush1
    radio_channel: 100
    devid: 0
    controller:
      FREQUENCY: 60.0
      vehicle_params:
        C_f: 41.7372
        C_r: 29.4662
        l_f: 0.163
        l_r: 0.168
        C_m1: 60.0
        C_m2: 3.0
        C_m3: 0.6
        m: 2.9
      LATERAL_CONTROL_GAINS:
        k1:
        - 0.00266
        - -0.0168
        - 0.0368
        - 0.0357
        k1_r:
        - -0.0008
        - 0.0442
        - -1.2247
        k2:
        - 0.0424
        - -0.268
        - 0.588
        - 0.57
        k2_r:
        - -0.0002
        - 0.0191
        - -0.9531
        k3:
        - 0.00952
        - -0.109
        - 0.469
        - 0.0322
      LONGITUDINAL_CONTROL_GAINS:
        C_m1: 60.0
        C_m2: 3.0
        C_m3: 0.6
        k1:
        - 0.0001
        - -0.0014
        - 0.0908
        k2:
        - -0.0025
        - 0.0298
        - 0.0095
        m: 2.9
      mocap_observer:
        CUTOFF: 2.0
        FREQUENCY: 60.0
        MARKER_OFFSET: 0.0
        MOCAP_EXTERNAL_TOPIC: /aimotion_mocap_node/rigid_bodies/<id>/pose
        POSE_TOPIC: /aimotion_mocap_node/rigid_bodies/JoeBushJr/pose
    crazy_observer:
      CUTOFF: 2.0
      FREQUENCY: 60.2
      MARKER_OFFSET: 0.0
    drive_bridge:
      MOTOR_LIMIT: 0.2
      STEERING_GAINS:
      - -0.90616
      - 0.54172
