drive_bridge:
  ros__parameters:
    STEERING_GAINS: [-0.90616, 0.54172] #[1/rad] [1] used for delta-> control input conversion
    MOTOR_LIMIT: 0.2 # The absolute limit of the motors reference input that normally ranges from -1 to 1

