parameter_server:
  ros__parameters:
   car_id: "JoeBushJr"
   crazy_observer:
    FREQUENCY: 60.2
    MARKER_OFFSET: 0.0 #0.2225 # [m] OptiTrack RigidBody center-point from the Vehicle's CoM
    CUTOFF: 2.0
   drive_bridge:
    STEERING_GAINS: [-0.90616, 0.54172]
    MOTOR_LIMIT: 0.2
   controller:
    FREQUENCY: 60.0
    LATERAL_CONTROL_GAINS:
     k1: [0.00266,-0.0168,0.0368,0.0357] #LPV base
     k2: [0.0424,-0.268,0.588,0.57]
     k3: [0.00952,-0.109,0.469,0.0322]
     k1_r: [-0.0008,0.0442, -1.2247] # GS
     k2_r: [-0.0002,0.0191,-0.9531]

    LONGITUDINAL_CONTROL_GAINS:
     k1: [0.0001,-0.0014,0.0908]
     k2: [-0.0025,0.0298,0.0095]
     m: 2.9 # [kg]
     C_m1: 60.0 # [N]
     C_m2: 3.0 # [Ns/m]
     C_m3: 0.6 # [N]
    mocap_observer:
     FREQUENCY: 60.0
     MARKER_OFFSET: 0.0 #0.2225 # [m] OptiTrack RigidBody center-point from the Vehicle's CoM
     MOCAP_EXTERNAL_TOPIC: "/aimotion_mocap_node/rigid_bodies/<id>/pose" # Specifies which topic the external mocap node publishes to. (only required if motion_tracking is set to external)
     POSE_TOPIC: /aimotion_mocap_node/rigid_bodies/JoeBushJr/pose
     CUTOFF: 2.0
